kind: Secret
apiVersion: v1

metadata:
  name: mysql-sec
#  namespace: my-ns # for main project
  namespace: helm-ns # for helm practice

type: opaque
data:
stringData:  # Use stringData to put plain text; K8s will encode it for you
  host: "database-v1.cih84c6osdd0.us-east-1.rds.amazonaws.com"
 # user: "iam_user" # for IAM Auth when use Load Balancer
  user: "admin" # when pain pass used
  dbname: "devops_db" # Update this from 'mysql' to your new database name # Based on your 'show databases' output
