kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2

metadata:
  name: helm-hpa
  namespace: helm-ns

spec:
  scaleTargetRef:
    name: helm-dep
    kind: Deployment
    apiVersion: apps/v1

  minReplicas: 1
  maxReplicas: 2

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
